version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build the App
          command: npm run build
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli
      - run:
          name: Sync to S3
          command: |
            aws s3 sync ./dist s3://my-vite-app-bucket --delete
      - run:
          name: Invalidate CloudFront (if using CloudFront)
          command: |
            aws cloudfront create-invalidation --distribution-id YOUR_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
          when: always
          
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
